version: '3'

services:
    mongodb:
        image: mongo:5
        restart: always
        volumes:
            - './mongodb:/data/db'
        networks:
            - unicovoit

    unicovoit:
        image: registry.ozna.me/unicovoit:latest
        container_name: unicovoit
        restart: always
        ports:
            - "3000:3000"
        volumes:
            -   './static/img:/usr/src/unicovoit/static/img'
        env_file:
            - .env
        environment:
            - MONGO_URL=mongodb
        networks:
            - unicovoit
        depends_on:
            - mongodb

networks:
    unicovoit:
        driver: bridge
