version: '3'

services:
    moodisc:
        image: iucovoit:latest
        container_name: iucovoit
        restart: always
        ports:
            - "3000:3000"
        env_file:
            - .env
