version: '3'

services:
    mongo:
        image: mongo:5
        restart: always
        volumes:
            - './mongodb:/data/db:Z'
            - "./mongo-entrypoint.sh:/docker-entrypoint-initdb.d/1-init-db.sh:Z"
        env_file:
            - .mongo.env

    unicovoit:
        image: registry.finxol.io/unicovoit:latest
        restart: always
        ports:
            - "3000:3000"
        volumes:
            -   './static/img:/usr/src/unicovoit/static/img:Z,U'
        env_file:
            - .env
        environment:
            - MONGO_URL=mongo
            - MONGO_PORT=27017
            - ADDOK_DOMAIN=addok.unicovoit.fr
