version: '3'

services:
    mongodb:
        image: mongo:5.0.6
        restart: always
        volumes:
            - './mongodb:/data/db'
        networks:
            - unicovoit
        ports:
            - "27017:27017"

    unicovoit:
        image: registry.ozna.me/iucovoit:latest
        container_name: unicovoit
        restart: always
        ports:
            - "3000:3000"
        env_file:
            - .env
        environment:
            - MONGO_URL=mongodb
        networks:
            - unicovoit
        depends_on:
            - mongodb

networks:
    unicovoit:
        driver: bridge
