version: '3'

services:
    mongo:
        image: mongo:5
        restart: always
        volumes:
            - './mongodb:/data/db'
            - "./mongo-entrypoint.sh:/docker-entrypoint-initdb.d/1-init-db.sh:z"
        env_file:
            - .mongo.env
        networks:
            - unicovoit

    unicovoit:
        image: registry.ozna.me/unicovoit:latest
        restart: always
        ports:
            - "3000:3000"
        volumes:
            -   './static/img:/usr/src/unicovoit/static/img'
        env_file:
            - .env
        environment:
            - MONGO_URL=mongo
            - ADDOK_DOMAIN=addok.unicovoit.fr
        networks:
            - unicovoit
        depends_on:
            - mongodb

networks:
    unicovoit:
        driver: bridge
