version: '3'

services:
    mongodb:
        image: mongo:5.0.6
        restart: always
        volumes:
            - './mongodb:/data/db'
        networks:
            - iucovoit

    iucovoit:
        image: iucovoit:latest
        container_name: iucovoit
        restart: always
        ports:
            - "3000:3000"
        env_file:
            - .env
        networks:
            - iucovoit
        depends_on:
            - mongodb

networks:
    iucovoit:
        driver: bridge
