version: '3'

services:
    mongodb:
        image: mongo:5.0.6
        restart: always
        volumes:
            - '/opt/iucovoit/mongodb:/bitnami/mongodb'
        ports:
            - "27017:27017"
