version: '2'

services:
    addok:
        image: etalab/addok
        ports:
            - "127.0.0.1:7878:7878"
        volumes:
            - ./addok-data/addok.conf:/etc/addok/addok.conf
            - ./addok-data/addok.db:/data/addok.db
            - ./tmp:/data/tmp
            - ./logs:/logs
        links:
            - addok-redis:redis
        environment:
            WORKERS: 1
            WORKER_TIMEOUT: 30
            LOG_QUERIES: 1
            LOG_NOT_FOUND: 1
            SLOW_QUERIES: 200

    addok-redis:
        image: etalab/addok-redis
        volumes:
            - ./addok-data/dump.rdb:/data/dump.rdb
