name: Auto Release


# only run when there is a new commit on main starting with "chore(release)"
on:
    push:
        branches:
            - main

# create a new github release
jobs:
    tag:
        runs-on: ubuntu-latest
        if: "startsWith(github.event.head_commit.message, 'chore(release): v')"
        steps:
            -   uses: actions/checkout@v2
            -   uses: christophebedard/tag-version-commit@v1
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    version_tag_prefix: 'chore(release): v'
                    version_regex: '[0-9]+\.[0-9]+\.[0-9]+'

    release:
        runs-on: ubuntu-latest
        if: "startsWith(github.event.head_commit.message, 'chore(release): v')"
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - uses: actions/setup-node@v3
              with:
                node-version: 16.x

            - run: npx changelogithub # or changelogithub@0.12 if ensure the stable result
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
